import type { Metadata } from "next"
import localFont from "next/font/local"
import "./globals.css"

const anticDidone = localFont({
  src: "./fonts/AnticDidone-Regular.ttf",
  variable: "--font-anticDidone",
})

const inter = localFont({
  src: [{ path: "./fonts/Inter_28pt-Light.ttf" }],
  variable: "--font-inter",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${anticDidone.variable} antialiased`}>
        {children}
      </body>
    </html>
  )
}
